spring:
  application:
    name: entity-service

  datasource:
    url: jdbc:mysql://localhost:3306/shikkha_sathi_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

#  flyway:
#    url: jdbc:mysql://localhost:3306/uber_db_local
#    user: root
#    password: root

server:
  port: 7476

logging:
  level:
    org:
      springframework:
        data: DEBUG
