spring:
  application:
    name: AuthService

  datasource:
    url: jdbc:mysql://localhost:3306/shikkha_sathi_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  expirationMs: 86400000 # 24 hours (in milliseconds)

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
    root: INFO
  file:
    name: logs/auth-service.log
    path: ./logs/
